# POST https://woodgrove-airlift-api.azurewebsites.net/OnAttributeCollectionStart
POST http://localhost:7071/api/CustomAuthenticationExtensionsAPI
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJub25

{
  "data": {
    "@odata.type": "string",
    "tenantId": "string",
    "authenticationEventListenerId": "string",
    "customAuthenticationExtensionId": "string",
    "authenticationContext": {
      "correlationId": "string",
      "client": {
        "ip": "string",
        "locale": "string",
        "market": "string"
      },
      "protocol": "string",
      "clientServicePrincipal": {
        "id": "string",
        "appId": "string",
        "appDisplayName": "string",
        "displayName": "string"
      },
      "resourceServicePrincipal": {
        "id": "string",
        "appId": "string",
        "appDisplayName": "string",
        "displayName": "string"
      },
      "user": {
        "displayName": "string",
        "id": "string",
        "userPrincipalName": "string",
        "userType": "string",
        "mail": "string"
      }
    },
    "userSignUpInfo": {
      "attributes": {
        "email": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        },
        "city2": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        },
        "country": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        },
        "displayName": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        },
        "extension_0cae61cc83e94edd978ec2fde3c5f2f3_SpecialDiet": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        },
        "extension_0cae61cc83e94edd978ec2fde3c5f2f3_PromoCode": {
          "value": "string",
          "@odata.type": "string",
          "attributeType": "string"
        }
      },
      "identities": [
        {
          "signInType": "string",
          "issuer": "string",
          "issuerAssignedId": "string"
        }
      ]
    }
  }
}